server:
  port: 6969
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/databasename
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    #username: abc123@gmail.com
    #password: from gmail security
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
